#!/bin/bash

if [ -z $OPENCV_VERSIONS_FILE ]; then
    OPENCV_VERSIONS_FILE=$HOME/etc/opencv-versions
fi

if [ $1 = "activate" ]; then
    eval OpenCVDir=$(awk "\$1==$2 { print \$2 }" $OPENCV_VERSIONS_FILE)
    if [ -z $OpenCVDir ]; then
        echo "Error: Version not recognized."
        exit 1
    fi
    export OPENCV_DIR=$OpenCVDir
    export LD_LIBRARY_PATH=$OpenCVDir/lib:$LD_LIBRARY_PATH
    export C_INCLUDE_PATH=$OpenCVDir/include:$C_INCLUDE_PATH
    export CPLUS_INCLUDE_PATH=$OpenCVDir/include:$CPLUS_INCLUDE_PATH
elif [ $1 = "deactivate" ]; then
    if [ -z $OPENCV_DIR ]; then
        echo "Error: OpenCV not activated."
        exit 1
    fi
    arr=($(echo $LD_LIBRARY_PATH | sed "s/:/\n/g" | grep -v "$OPENCV_DIR"))
    export LD_LIBRARY_PATH=$(echo "${arr[*]}" | sed "s/\s\+/:/g")
    arr=($(echo $C_INCLUDE_PATH | sed "s/:/\n/g" | grep -v "$OPENCV_DIR"))
    export C_INCLUDE_PATH=$(echo "${arr[*]}" | sed "s/\s\+/:/g")
    arr=($(echo $CPLUS_INCLUDE_PATH | sed "s/:/\n/g" | grep -v "$OPENCV_DIR"))
    export CPLUS_INCLUDE_PATH=$(echo "${arr[*]}" | sed "s/\s\+/:/g")
    export OPENCV_DIR=
elif [ $1 = "install" ]; then
    if [ -f $OPENCV_VERSIONS_FILE ]; then
        content=$(awk "\$1 != $2 { print \$0 }" $OPENCV_VERSIONS_FILE)
        echo $content > $OPENCV_VERSIONS_FILE
        echo "$2 $3" >> $OPENCV_VERSIONS_FILE
    else
        echo "$2 $3" > $OPENCV_VERSIONS_FILE
    fi
elif [ $1 = "uninstall" ]; then
    if [ -f $OPENCV_VERSIONS_FILE ]; then
        content=$(awk "\$1 != $2 { print \$0 }" $OPENCV_VERSIONS_FILE)
        echo $content > $OPENCV_VERSIONS_FILE
    fi
fi

