#!/bin/bash

cmdname=$(basename $0)

if [ -z $OPENCV_VERSIONS_PATH ]; then
    OPENCV_VERSIONS_PATH=$HOME/etc/opencv-versions
fi

if [[ $1 = "activate" ]]; then
    VersionFiles=($(ls $OPENCV_VERSIONS_PATH/*.conf))
    for versionFilesItem in $VersionFiles; do
        if [ $(basename $versionFilesItem | sed "s/.conf$//g") = $2 ]; then
            VersionFile=$versionFilesItem
        fi
    done
    if [ -z $VersionFile ]; then
        echo "Error: Version not recognized."
        exit 1
    fi
    if [ $OpenCVVersion ]; then
        source $0 deactivate
    fi
    while read line; do
        split=($(echo $line | sed "s/=/ /g"))
        pname=$(echo ${split[0]} | sed "s/^\s\+//" | sed "s/\s\+$//")
        pval=$(echo ${split[1]} | sed "s/^\s\+//" | sed "s/\s\+$//")
        if [ $pname = "include_path" ]; then OpenCVIncludePath=$pval
        elif [ $pname = "lib_path" ]; then OpenCVLibPath=$pval
        fi
    done < $VersionFile
    export OpenCVVersion=$2
    export OpenCVIncludePath
    export OpenCVLibPath
    export LIBRARY_PATH=$OpenCVLibPath:$LD_LIBRARY_PATH
    export LD_LIBRARY_PATH=$OpenCVLibPath:$LD_LIBRARY_PATH
    export C_INCLUDE_PATH=$OpenCVIncludePath:$C_INCLUDE_PATH
    export CPLUS_INCLUDE_PATH=$OpenCVIncludePath:$CPLUS_INCLUDE_PATH
elif [[ $1 = "deactivate" ]]; then
    if [ -z $OpenCVVersion ]; then
        echo "Error: OpenCV not activated."
        exit 1
    fi
    if [ $OpenCVLibPath ]; then
        arr=($(echo $LD_LIBRARY_PATH | sed "s/:/\n/g" | grep -v "$OPENCV_DIR"))
        export LD_LIBRARY_PATH=$(echo "${arr[*]}" | sed "s/\s\+/:/g")
        arr=($(echo $LIBRARY_PATH | sed "s/:/\n/g" | grep -v "$OPENCV_DIR"))
        export LIBRARY_PATH=$(echo "${arr[*]}" | sed "s/\s\+/:/g")
    fi
    if [ $OpenCVIncludePath ]; then
        arr=($(echo $C_INCLUDE_PATH | sed "s/:/\n/g" | grep -v "$OPENCV_DIR"))
        export C_INCLUDE_PATH=$(echo "${arr[*]}" | sed "s/\s\+/:/g")
        arr=($(echo $CPLUS_INCLUDE_PATH | sed "s/:/\n/g" | grep -v "$OPENCV_DIR"))
        export CPLUS_INCLUDE_PATH=$(echo "${arr[*]}" | sed "s/\s\+/:/g")
    fi
    export OpenCVVersion=
else
	# print help texts
	cat << EOF
USAGE
	$cmdname <activate|deactivate> [version]

DESCRIPTION
	Activate certain OpenCV version. Activation will add corresponding paths to \$C_INCLUDE_PATH, \$CPLUS_INCLUDE_PATH, \$LIBRARY_PATH and \$LD_LIBRARY_PATH. Corresponding paths will also be stored into \$OpenCVIncludePath and \$OpenCVLibPath.

CONFIGUATION
	Information of each OpenCV version should be written in a single configuration file under \$OPENCV_VERSIONS_PATH (default is \$HOME/etc/opencv-versions). File name should be <version>.conf File content should be like this:
		lib_path=/path/to/directory/of/so/files
		include_path=/path/to/directory/of/header/files

EOF
fi

